# https://qiita.com/chihiro/items/8b2918ceb709cb9079e8
name: workflow_dispatch sample

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Name'
        required: true

jobs:
  printLog:
    runs-on: ubuntu-latest

    steps:
    - name: print log
      run: echo "Hello! ${{ github.event.inputs.name }}"
